version: "3.3"

services:

  mongo:
    image: mongo:3
    container_name: mongo
    ports:
      - "6379:6379"
    networks:
      - skynet

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - skynet
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
    depends_on:
      - mongo

  graylog:
    image: graylog/graylog:3.0.1
    container_name: graylog
    ports:
      - "9000:9000"
      - "12201:12201"
    networks:
      - skynet
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
      - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=maildev
      - GRAYLOG_TRANSPORT_EMAIL_PORT=25
      - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
      - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
      - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
      - GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES=true
      - GRAYLOG_ALLOW_HIGHLIGHTING=true
    depends_on:
      - mongo
      - es

networks:
  skynet:
    external:
      name: skynet    